import type { CaseStats } from '$lib/types/frontendTypes';


interface NysCases {
	internal_case_id: string;
	gender?: string | null;
	race?: string | null;
	ethnicity?: string | null;
	age_at_crime?: string | null;
	age_at_arrest?: string | null;
	court_name?: string | null;
	court_ori?: string | null;
	county_name?: string | null;
	district?: string | null;
	region?: string | null;
	court_type?: string | null;
	judge_name?: string | null;
	offense_month?: string | null;
	offense_year?: string | null;
	arrest_month?: string | null;
	arrest_year?: string | null;
	arrest_type?: string | null;
	top_arrest_law?: string | null;
	top_arrest_article_section?: string | null;
	top_arrest_attempt_indicator?: string | null;
	top_charge_at_arrest?: string | null;
	top_charge_severity_at_arrest?: string | null;
	top_charge_weight_at_arrest?: string | null;
	top_charge_at_arrest_violent_felony_ind?: string | null;
	case_type?: string | null;
	first_arraign_date?: string | null;
	top_arraign_law?: string | null;
	top_arraign_article_section?: string | null;
	top_arraign_attempt_indicator?: string | null;
	top_charge_at_arraign?: string | null;
	top_severity_at_arraign?: string | null;
	top_charge_weight_at_arraign?: string | null;
	top_charge_at_arraign_violent_felony_ind?: string | null;
	hate_crime_ind?: string | null;
	arraign_charge_category?: string | null;
	representation_type?: string | null;
	app_count_arraign_to_dispo_released?: string | null;
	app_count_arraign_to_dispo_detained?: string | null;
	app_count_arraign_to_dispo_total?: string | null;
	def_attended_sched_pretrials?: string | null;
	remanded_to_jail_at_arraign?: string | null;
	ror_at_arraign?: string | null;
	bail_set_and_posted_at_arraign?: string | null;
	bail_set_and_not_posted_at_arraign?: string | null;
	nmr_at_arraign?: string | null;
	release_decision_at_arraign?: string | null;
	representation_at_securing_order?: string | null;
	pretrial_supervision_at_arraign?: string | null;
	contact_pretrial_service_agency?: string | null;
	electronic_monitoring?: string | null;
	travel_restrictions?: string | null;
	passport_surrender?: string | null;
	no_firearms_or_weapons?: string | null;
	maintain_employment?: string | null;
	maintain_housing?: string | null;
	maintain_school?: string | null;
	placement_in_mandatory_program?: string | null;
	removal_to_hospital?: string | null;
	obey_order_of_protection?: string | null;
	obey_court_conditions_family_offense?: string | null;
	other_nmr?: string | null;
	order_of_protection?: string | null;
	first_bail_set_cash?: string | null;
	first_bail_set_credit?: string | null;
	first_insurance_company_bail_bond?: string | null;
	first_secured_surety_bond?: string | null;
	first_secured_app_bond?: string | null;
	first_unsecured_surety_bond?: string | null;
	first_unsecured_app_bond?: string | null;
	first_partially_secured_surety_bond?: string | null;
	partially_secured_surety_bond_perc?: string | null;
	first_partially_secured_app_bond?: string | null;
	partially_secured_app_bond_perc?: string | null;
	bail_made_indicator?: string | null;
	warrant_ordered_btw_arraign_and_dispo?: string | null;
	dat_wo_ws_prior_to_arraign?: string | null;
	first_bench_warrant_date?: string | null;
	non_stayed_wo?: string | null;
	num_of_stayed_wo?: string | null;
	num_of_row?: string | null;
	docket_status?: string | null;
	disposition_type?: string | null;
	disposition_detail?: string | null;
	dismissal_reason?: string | null;
	disposition_date?: string | null;
	most_severe_sentence?: string | null;
	top_conviction_law?: string | null;
	top_conviction_article_section?: string | null;
	top_conviction_attempt_indicator?: string | null;
	top_charge_at_conviction?: string | null;
	top_charge_severity_at_conviction?: string | null;
	top_charge_weight_at_conviction?: string | null;
	top_charge_at_conviction_violent_felony_ind?: string | null;
	days_arraign_remand_first_released?: string | null;
	known_days_in_custody?: string | null;
	days_arraign_bail_set_to_first_posted?: string | null;
	days_arraign_bail_set_to_first_release?: string | null;
	days_arraign_to_dispo?: string | null;
	ucmslivedate?: string | null;
	prior_vfo_cnt?: string | null;
	prior_nonvfo_cnt?: string | null;
	prior_misd_cnt?: string | null;
	pend_vfo?: string | null;
	pend_nonvfo?: string | null;
	pend_misd?: string | null;
	supervision?: string | null;
	rearrest?: string | null;
	rearrest_date?: string | null;
	rearrest_firearm?: string | null;
	rearrest_date_firearm?: string | null;
	arr_cycle_id?: string | null;
}


export type CountyModel = {
	county_name: string;
	county_id: string;
	case_count?: number;
	remand_at_arraign?: number;
	ror_at_arraign?: number;
	nmr_at_arraign?: number;
	release_at_arraign?: number;
	bail_set_at_arraign?: number;
	total_bail_set?: number;
	average_bail_set?: number;
	percent_ror?: number;
	percent_nmr?: number;
	percent_release?: number;
	percent_remand?: number;
	percent_bail_set?: number;
	unknown_at_arraign?: number;
	percent_unknown?: number;
	judges?: JudgeModel;
}

export type JudgeModel = {
	judge_name: string;
	judge_id: string;
	case_count?: number;
	remand_at_arraign?: number;
	ror_at_arraign?: number;
	nmr_at_arraign?: number;
	release_at_arraign?: number;
	bail_set_at_arraign?: number;
	total_bail_set?: number;
	average_bail_set?: number;
	percent_ror?: number;
	percent_nmr?: number;
	percent_release?: number;
	percent_remand?: number;
	percent_bail_set?: number;
	unknown_at_arraign?: number;
	percent_unknown?: number;
	counties?: CountyModel;
}

export type JudgeModelOrCountyModel = {
	case_count?: number;
	remand_at_arraign?: number;
	ror_at_arraign?: number;
	nmr_at_arraign?: number;
	release_at_arraign?: number;
	bail_set_at_arraign?: number;
	total_bail_set?: number;
	average_bail_set?: number;
	percent_ror?: number;
	percent_nmr?: number;
	percent_release?: number;
	percent_remand?: number;
	percent_bail_set?: number;
	unknown_at_arraign?: number;
	percent_unknown?: number;
}


export type CaseModel = {
	internal_case_id: string;
	gender?: string;
	ethnicity?: string;
	age_at_crime?: number;
	age_at_arrest?: number;
	offense_month?: string;
	offense_year?: string;
	arrest_month?: string;
	arrest_year?: string;
	arrest_type?: string;
	top_arrest_law?: string;
	top_arrest_article_section?: string;
	top_arrest_attempt_indicator?: string;
	top_charge_severity_at_arrest?: string;
	top_charge_weight_at_arrest?: string;
	top_charge_at_arrest_violent_felony_ind?: string;
	case_type?: string;
	first_arraign_date?: string;
	top_arraign_law?: string;
	top_arraign_article_section?: string;
	top_arraign_attempt_indicator?: string;
	top_charge_at_arraign?: string;
	top_severity_at_arraign?: string;
	top_charge_weight_at_arraign?: string;
	top_charge_at_arraign_violent_felony_ind?: string;
	arraign_charge_category?: string;
	app_count_arraign_to_dispo_released?: string;
	app_count_arraign_to_dispo_detained?: string;
	app_count_arraign_to_dispo_total?: string;
	def_attended_sched_pretrials?: string;
	remanded_to_jail_at_arraign?: string;
	ror_at_arraign?: string;
	bail_set_and_posted_at_arraign?: string;
	bail_set_and_not_posted_at_arraign?: string;
	nmr_at_arraign?: string;
	release_decision_at_arraign?: string;
	representation_at_securing_order?: string;
	pretrial_supervision_at_arraign?: string;
	contact_pretrial_service_agency?: string;
	electronic_monitoring?: string;
	travel_restrictions?: string;
	passport_surrender?: string;
	no_firearms_or_weapons?: string;
	maintain_employment?: string;
	maintain_housing?: string;
	maintain_school?: string;
	placement_in_mandatory_program?: string;
	removal_to_hospital?: string;
	obey_order_of_protection?: string;
	obey_court_conditions_family_offense?: string;
	other_nmr?: string;
	order_of_protection?: string;
	first_bail_set_cash?: string;
	first_bail_set_credit?: string;
	first_insurance_company_bail_bond?: string;
	first_secured_surety_bond?: string;
	first_secured_app_bond?: string;
	first_unsecured_surety_bond?: string;
	first_unsecured_app_bond?: string;
	first_partially_secured_surety_bond?: string;
	partially_secured_surety_bond_perc?: string;
	first_partially_secured_app_bond?: string;
	partially_secured_app_bond_perc?: string;
	bail_made_indicator?: string;
	warrant_ordered_btw_arraign_and_dispo?: string;
	dat_wo_ws_prior_to_arraign?: string;
	first_bench_warrant_date?: string;
	non_stayed_wo?: string;
	num_of_stayed_wo?: string;
	num_of_row?: string;
	docket_status?: string;
	disposition_type?: string;
	disposition_detail?: string;
	dismissal_reason?: string;
	disposition_date?: string;
	most_severe_sentence?: string;
	top_conviction_law?: string;
	top_conviction_article_section?: string;
	top_conviction_attempt_indicator?: string;
	top_charge_at_conviction?: string;
	top_charge_severity_at_conviction?: string;
	top_charge_weight_at_conviction?: string;
	top_charge_at_conviction_violent_felony_ind?: string;
	days_arraign_remand_first_released?: string;
	known_days_in_custody?: string;
	days_arraign_bail_set_to_first_posted?: string;
	days_arraign_bail_set_to_first_release?: string;
	days_arraign_to_dispo?: string;
	ucmslivedate?: string;
	prior_vfo_cnt?: string;
	prior_nonvfo_cnt?: string;
	prior_misd_cnt?: string;
	pend_vfo?: string;
	pend_nonvfo?: string;
	pend_misd?: string;
	supervision?: string;
	rearrest?: string;
	rearrest_date?: string;
	rearrest_firearm?: string;
	rearrest_date_firearm?: string;
	arr_cycle_id?: string;
	race_id?: string;
	court_id?: string;
	county_id?: string;
	top_charge_id?: string;
	representation_id?: string;
	judge_id?: string;
	case_uuid: string;
	district_id?: string;
	counties?: CountyModel;
	judges?: JudgeModel;
	representation?: RepresentationModel;
	crimes?: CrimeModel;
}

export type CrimeModel = {
	crime_uuid: string;
	top_charge_at_arrest: string;
	average_bail_amount?: number;
	number_of_cases?: number;
}

export type RepresentationModel = {
	representation_uuid: string;
	representation_type: string;
	average_bail_amount?: number;
	number_of_cases?: number;
	average_known_days_in_custody?: number;
	remanded_percentage?: number;
	bail_set_percentage?: number;
	disposed_at_arraign_percentage?: number;
	ror_percentage?: number;
	nonmonetary_release_percentage?: number;
}
